- name: Clone and build ppcdis
  run: |
    git clone --depth 1 https://github.com/SeekyCt/ppcdis.git
    ls ppcdis/Cargo.toml && echo "Cargo.toml found" || echo "Cargo.toml missing"
    cargo build --release --manifest-path ppcdis/Cargo.toml
    cp ppcdis/target/release/ppcdis .
    rm -rf ppcdis
